### PR TITLE
Issue-322: corosync configuration for non-kubernetis env

### PR DESCRIPTION
**Pull request by SergeyKaydalov**
#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.
- [ ] Change modifies documentation or comments only.

#### Description

This should fix a problem with corosync.conf in a standalone mode

#### Which issue this PR fixes

fixes #

### CODE REVIEW

**Comment by dyusupov** [comment]
:star: PR built and available in a preview environment **nexenta-edgefs-pr-331**

**Comment by dyusupov** [comment]
:star: PR built and available in a preview environment **nexenta-edgefs-pr-331**

**Comment by dyusupov** [comment]
:star: PR built and available in a preview environment **nexenta-edgefs-pr-331**

**Comment by dyusupov** [comment]
> Now non k8s env will only support one node cluster?

multi-node.. it used to work, we regressed a bit - so, this pull req should fix it. Let's wait for more from Sergey before we squash or merge.

**Comment by SergeyKaydalov** [comment]
Refactored a little bit. The PR is about how the corosync.conf is created/updated.
It used to be generated by `efscli config ...` However, later, we added a tool corosync-pod-watcher to generate/update this file. But it works only in k8s environment. So with this pull request, we reverted changes in `efscli config ...` so now non-k8s configurations should be working as well. Both multi- or single-node configurations should be good.

**Comment by dyusupov** [comment]
:star: PR built and available in a preview environment **nexenta-edgefs-pr-331**

**Comment by dyusupov** [comment]
:star: PR built and available in a preview environment **nexenta-edgefs-pr-331**

**Pull request merged**
